### ISSUE TITLE
RDKit requirement

### ISSUE THREAD

**Issue by stevenbennett96** [lukasturcani/stk#119]
Can't use stk without RDKit being installed, meaning it should be a dependency is setup.py.

![image](https://user-images.githubusercontent.com/25821470/80753716-a2d2db80-8b25-11ea-88d5-a0dcf17631fd.png)

**Comment by lukasturcani** [comment]
setup.py AFAIK is only compatible with pip dependencies, and rdkit is not installable with pip.
