### ISSUE TITLE
mol.write folder not found

### ISSUE THREAD

**Issue by fiszczyp** [lukasturcani/stk#13]
When using population.write(), the output folder is created when it does not exist. In contrast, molecule.write() requires the folder to exist, otherwise a FileNotFoundError is raised.

**Comment by lukasturcani** [comment]
This is intended behaviour. Population.write writes the folder, whereas Molecule.write writes the file.
Population is a collection of molecules which is why it writes a folder. A Population is to a Molecule what a folder is to a file.
