### ISSUE TITLE
Add unaligning vertices

### ISSUE THREAD

**Issue by lukasturcani** [lukasturcani/stk#156]
Most topologies at the moment expect functional groups with different placer ids. They can be made more tolerant by using a vertex which only places and doe not do any alignment, for cases where there is only 1 placer id in the entire molecule, across all functional groups.

Maybe warn the user when it is used?

**Comment by lukasturcani** [comment]
@andrewtarzia - is gonna take the Linear class

**Comment by andrewtarzia** [comment]
@lukasturcani the linear class already had an unaligning vertex, so just had to implement the replacement of linear vertices with an unaligning vertex if placer_ids is 1 -- this should be similar for many classes.

**Comment by andrewtarzia** [comment]
@lukasturcani I would say we have covered this?

**Comment by lukasturcani** [comment]
Agreed!
