### ISSUE TITLE
Get periodic unit cell.

### ISSUE THREAD

**Issue by andrewtarzia** [lukasturcani/stk#183]
Currently, periodic molecules (equivalent to .ConstructuedMolecule) do not have an easy way of accessing the periodic unit cell. It is used in the construction stage.

Suggesting ConstructedMolecule.get_enclosing_cell():
for periodic molecules, the topology graph._periodic is True: this is the unit cell.
else (i.e. for all other Molecule): This is just some enclosing cube, which does have its uses (can be calculated by projecting atom positions along basis vectors).

An alternative is to have PeriodicConstructedMolecule subclass, which handles this and any future periodic only properties.

I prefer option one; two features for the price of minor ambiguity. But I am unsure of how much overlap is results from it.

**Comment by lukasturcani** [comment]
#182
