### ISSUE TITLE
.with_structure_from_file methods should handle formatting changes for periodic file types

### ISSUE THREAD

**Issue by andrewtarzia** [lukasturcani/stk#227]
Only .pdb and .coord file types are relevant. Unsure what the impact is at this point, but the change in file formatting may break the current code if it expects a rigid formatting.

**Comment by lukasturcani** [comment]
Do we have a way forward with this for .pdb files?

**Comment by andrewtarzia** [comment]
We do not have a with_structure_from_file for PDB files because we use the RDKIT function for PDB files in BuildingBlock.

The solution would actually just be to add a with_structure_from_file for pdb that uses the rdkit code - thoughts?

**Comment by lukasturcani** [comment]
Yes, looks like we use the rdkit pdb reader for `BuildingBlock.init_from_file`. We also have our own, custom, pdb writer for `Molecule.write`. Remind me, what exactly do we want to be able to do? Just read the file, and make sure the function does not crash in cases where periodic parametes are? Do we want to read the periodic parameters? What would the periodic parameters be? What is generating these periodic files we are trying to read?

**Comment by andrewtarzia** [comment]
-  Remind me, what exactly do we want to be able to do? **Read a PDB without crashing if the file is not fitting a rigid format (not relevant for pdb because we do not handle it)**
- Just read the file, and make sure the function does not crash in cases where periodic parametes are defined in the file? **Indeed**.
- Do we want to read the periodic parameters? What would the periodic parameters be? What is generating these periodic files we are trying to read?: **At this stage, no, stk does not update cell parameters when updating a structure - I do not see it needing to do this. stko does though. Optimisations generate new unit cells.**

**Comment by lukasturcani** [comment]
Ok cool. So it does seem like just adding the rdkit reader to the update function should do the trick. But if this is so, I wonder why pdb is not supported already? Was there an issue, or was it just an innocent omission?

I guess there's only one way to find out, add it and see if the tests pass. Are you happy to do it? I could try if you're busy, but I'm not sure how to go about getting good test cases.

**Comment by andrewtarzia** [comment]
Ya, I will have a crack this afternoon. I think the omission was accidental, because general use-cases are always .mol files
