### ISSUE TITLE
Include Periodic COF topology graphs in docs?

### ISSUE THREAD

**Issue by andrewtarzia** [lukasturcani/stk#257]
Was this not done on purpose?

**Comment by ltalirz** [comment]
I guess [they are present now](https://stk.readthedocs.io/en/stable/stk.molecular.topology_graphs.cof.cof.html)

![Uploading image.png…]()

**Comment by lukasturcani** [comment]
Hi @ltalirz ! Yep, thanks for pointing this out, I think you're right, I'm gonna close this now.
