### ISSUE TITLE
Currently, none of these optimizers can modify the periodic cell.

### ISSUE THREAD

**Issue by andrewtarzia** [lukasturcani/stk#278]
Currently, none of these optimizers can modify the periodic cell. 

This should be a separate issue as it requires modifying the API of the PeriodicInfo class (from my experience).

In this issue - I will add a Collapser class that can collapse the periodic information as well, during the process.

_Originally posted by @andrewtarzia in https://github.com/lukasturcani/stk/issues/262#issuecomment-757498426_

**Comment by lukasturcani** [comment]
Fixed by #313.
