### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by stevenkbennett** [lukasturcani/stk#279]
![image](https://user-images.githubusercontent.com/25821470/104625209-64b62180-568c-11eb-99e1-64854e70af60.png)

Says fg.with_atoms() when it should say amine.with_atoms()

**Comment by stevenbennett96** [comment]
On this page: https://stk.readthedocs.io/en/latest/stk.molecular.functional_groups.functional_groups.functional_group.html

**Comment by stevenbennett96** [comment]
Also should nitrogen, hydrogen and hydrogen be in something itterable?

**Comment by lukasturcani** [comment]
tyty!

nah , I prefer they are not grouped together, because the order ambiguous
