### ISSUE TITLE
Create a general Vertex and Edge class.

### ISSUE THREAD

**Issue by lukasturcani** [lukasturcani/stk#31]
At the moment, when new topologies are created, tools to assembled a new topology graph easily do not really exist and are written from scratch for each class of topologies. It would be good to create a general Vertex and Edge class which can be used for any class of topologies. These won't have to be used, but should be available when desired.

**Comment by andrewtarzia** [comment]
I would like to work on this. My first goal is to get the MOC topologies working, but they will use a generalized Vertex and Edge that is inspired by the COF class. 

Upon completion of the first few test cases of MOCs, the generalized Edge and Vertex can be implemented for other topologies?

**Comment by lukasturcani** [comment]
Ok, sounds good to me!
