### ISSUE TITLE
Accessing private vertex classes 

### ISSUE THREAD

**Issue by andrewtarzia** [lukasturcani/stk#344]
All implemented vertex classes are "private" with names like "_LinearCageVertex". This makes them difficult to access by users who may want to implement a new topology graph in their own code without reimplementing the vertex classes (which makes no sense).

Suggestion is to make them as accessible as other classes; i.e. 

```python
import stk

vertex = stk.cage.LinearCageVertex(...)
```

**Comment by lukasturcani** [comment]
I guess I can also just rename it to `stk.cage.LinearVertex` when I do this.
