### ISSUE TITLE
Implement a metal coordination environment pre optimizer class

### ISSUE THREAD

**Issue by andrewtarzia** [lukasturcani/stk#35]
This will be part of the implementation of metal organic systems and will develop an optimizer to be the first part of a sequence which assists stk in maintaining desired metal geometry. I.e. pre restricted optimization, the user would perform this new optimization.

**Comment by andrewtarzia** [comment]
I would like to work on this.

**Comment by lukasturcani** [comment]
Sounds interesting, though I'm not exactly sure what it would do / how it would do it.
Whats the input and whats the output?
Does it use 3rd party software? How does it achieve the change in structure? How does it force a restriction on structure?

**Comment by andrewtarzia** [comment]
There are details that need to be figured out but it won't use third party
software and the API should be the same as the simple optimizer classes
(i.e. UFF).

Abstract thoughts at this stage but this will be required eventually either
way.

**Comment by lukasturcani** [comment]
The main issue I see with this is that an optimizer only modifies the structure of a molecule. So if you want an optimizer to do a restricted optimization, the solution is to add a parameter to the `__init__` of the optimizer which allows you to do restricted optimizations. The solution would not be to pass it through a different optimizer first.

**Comment by lukasturcani** [comment]
Irrelevant as of #95.
