### ISSUE TITLE
Implement better tests for all xTB class (XTB, XTBEnergy, XTBExtractor)

### ISSUE THREAD

**Issue by andrewtarzia** [lukasturcani/stk#38]
The current tests could be improved by using mock classes to test the output of the xTB calculations.

**Comment by lukasturcani** [comment]
A mock xtb extractor should be provided for the xtb tests. The tests should check that the files got written by running xtb and then check that the values returned by xtb match those supplied by the mock

**Comment by andrewtarzia** [comment]
In particular, tests should not rely on nondeterministic things (i.e. the presence of a negative frequency as in .test_xtb_negfreq())

**Comment by lukasturcani** [comment]
Fixed in #95
