### ISSUE TITLE
bug using stk.ETKDG for long polymers

### ISSUE THREAD

**Issue by andrewtarzia** [lukasturcani/stk#41]
When optimizing a polymer with n=5, an overflow error is produced within ETKDG.optimize(). It seems to the conf_id variable having a negative sign when calling RemoveConformer, which takes an unsigned int. MWE.txt is a minimum working example that requires the two attached mol files (change ending from .txt to .mol).

[MWE.txt](https://github.com/lukasturcani/stk/files/3322476/MWE.txt)
[CNben.txt](https://github.com/lukasturcani/stk/files/3322475/CNben.txt)
[SBI.txt](https://github.com/lukasturcani/stk/files/3322477/SBI.txt)

**Comment by lukasturcani** [comment]
I believe this is an issue with rdkit etkdg, due to the number of atoms being too large to embed. This issue is best raised there.
