### ISSUE TITLE
Add a base Writer class

### ISSUE THREAD

**Issue by andrewtarzia** [lukasturcani/stk#430]
Based on the existing Writers, a base class would have:

- a `write` method
- a `to_string` method
- a `_write_content` method

Using a base class may clean up the other writer classes and allow for extension by users using inheritance.

**Comment by lukasturcani** [comment]
Hmm, I think there was some reason we didn't do this. I wonder if it is in any of the commit messages...

I think the main argument is that while the would all have a `write` and a `to_string` method. It does not mean that all the writers would have the same arguments to those methods. This is also a requirement for having a shared base class. I think assuming that they would all have the same arguments is a pretty strong assumption, and I do not generally see the advantage of making it. For example, if you want to write periodic systems, you can imagine an additional argument to do with the periodic cell, which makes no sense to include in the `write()` method of non-periodic writers. In fact, I think https://stk.readthedocs.io/en/stable/stk.molecular.writers.mdl_mol.html and https://stk.readthedocs.io/en/stable/stk.molecular.writers.pdb.html are actually example of this .

A design point of on the use of a base class. The use of a shared base class, means that users would be able to provide either a `MolWriter`or a `PdbWriter` interchangeable, without caring which one is which. But I find it hard to think of an example with treating writers as abstract, interchangeable entities is beneificial. I think normally when you write code, you want to be explicit about which actual writer you are using, therefore referencing them through a shared, abstract interface I think in practice add little value -> though counter-examples are highly appreciated!

**Comment by andrewtarzia** [comment]
This is perfect and very clear. A description of why we made that choice was needed because I know we did it on purpose.
