### ISSUE TITLE
subprocess.call() in xtb functions fails with Shell=False

### ISSUE THREAD

**Issue by andrewtarzia** [lukasturcani/stk#47]
Only occurs if unlimited_memory=False.

Using Shell=True in all cases introduces security risks due to the possibility of external input into the command.

A better alternative is to use something other than subprocess.call or to remove the possibility of external input into the command. Currently, the input of strings for xTB arguments is a security risk.

**Comment by lukasturcani** [comment]
I don't understand how this causes a security issue, can you give me a more clear example?

**Comment by andrewtarzia** [comment]
Because arguments are strings, any user could technically insert ';rm -rf /
;' and it would run in the shell. Just an example.

**Comment by lukasturcani** [comment]
Yes, but the user is welcome to do that. I don't think mutilating your own computer is a security risk. It's a security risk if someone else can damage your computer. The user can modify the source code of stk to do anything anyway, as this is open source software

**Comment by andrewtarzia** [comment]
Ok. We can close this issue then.

**Comment by andrewtarzia** [comment]
Please reopen this issue because the actual problem was not solved.

i.e. if shell=False, sp.call() fails for xtb.
