### ISSUE TITLE
Fitness Calcuation should operate on MoleculeRecord

### ISSUE THREAD

**Issue by lukasturcani** [lukasturcani/stk#473]
It's a bit weird that it takes a molecule, because the rest of the EA's operations work on a recrod, and `MoleculeRecord` may have information useful for the calculation of a fitness value.

**Comment by andrewtarzia** [comment]
This requires changing the `stk.ea.Implementation` class, but no others.

**Comment by andrewtarzia** [comment]
Specifically the `_with_fitness_values` method of that class.

**Comment by andrewtarzia** [comment]
Also, requires documentation changes to all `FitnessCalculator` classes.
