### ISSUE TITLE
Fix links

### ISSUE THREAD

**Issue by lukasturcani** [lukasturcani/stk#494]
https://stk.readthedocs.io/en/latest/_autosummary/stk.Alcohol.html
![image](https://github.com/lukasturcani/stk/assets/17861210/2ce506a2-eb94-46a3-b697-596b729fd800)

**Comment by andrewtarzia** [comment]
This is completed in the latest stable docs. Check and close @lukasturcani ?

**Comment by lukasturcani** [comment]
interesting --- i wonder if its due to an update in sphinx? i dont think i / anyone else fixed this manually?

**Comment by andrewtarzia** [comment]
No idea, but it seems solved to me?

**Comment by lukasturcani** [comment]
yeah same -- will close

mostly worried that its not fixed everywhere but if so we can just open a new issue
