### ISSUE TITLE
AttributeError: module 'stk' has no attribute 'small'

### ISSUE THREAD

**Issue by wangyingyu1993** [lukasturcani/stk#530]
An error occurs when running stk.ConstructedMolecule(stk.small.NCore(......)): AttributeError: module 'stk' has no attribute 'small'.

**Comment by andrewtarzia** [comment]
Hey @wangyingyu1993 , I am going to assume you are running an old stk on Python < 3.11. If you update Python and stk, you should have access to `stk.small.NCore`
