### ISSUE TITLE
Default, consistent, coordinates from stk conformer generation differ on mac compared to unix.

### ISSUE THREAD

**Issue by andrewtarzia** [lukasturcani/stk#535]
stk uses seeds to obtain constant random numbers for the same molecules. This mostly effects conformer generation. In the tests, we compare generated structures to known structures to ensure this is true, but this is not checked on mac, which seems to provide different outcomes. I expect that mac would also be consistent (with themselves), but the tests will fail on mac because of this.

I am not sure how to solve this, but posting it for awareness/memory.

**Comment by andrewtarzia** [comment]
I also assumed rdkit was the culprit, not stk. But I changed the title.

**Comment by lukasturcani** [comment]
yeah im not sure much can be done about this. close as a wont fix?

**Comment by andrewtarzia** [comment]
I wasn't sure where the best notice for this would be, hence the issue is good for users. What do you think?

**Comment by lukasturcani** [comment]
i think that different results being expected on different chips should be taken for granted. i dont think we should have an open issue for something we can't do anything about

**Comment by andrewtarzia** [comment]
Agreed, close as unplanned. Ty!
