### ISSUE TITLE
FitnessFunction fitness calculator

### ISSUE THREAD

**Issue by lukasturcani** [lukasturcani/stk#77]
Simlilar to FitnessValue but takes a function which gets called on a molecule and returns  a value

For example

```python

class FitnessFunction(FitnessCalculator):
    def __init__(self, fitness_fn, use_cache=False):
        self._fitness_fn = fitness_fn
        super().__init__(use_cache=use_cache)

    def get_fitness(self, mol):
        return self._fitness_fn(mol)

```

A use case can be generating random fitness values

```python

a = FitnessFunction(lambda mol: np.random.uniform(0, 100))
b = FitnessFunction(lambda mol: np.random.normal())

# sample from uniform dist
f1= a.get_fitness(some_mol)
# sample from gaussian dist
f2 = b.get_fitness(some_mol)

```

Of course this is still useful if you just want define a simple fitness function in the input file and dont want to define your own fitness calculator.

**Comment by lukasturcani** [comment]
@stevenbennett96

is this something like what you had in mind?

**Comment by stevenbennett96** [comment]
Yes, this is exactly what I had in mind!

**Comment by lukasturcani** [comment]
I just realized this makes FitnessValue redundant as well.

**Comment by lukasturcani** [comment]
Well it was nice while we had it.
