### ISSUE TITLE
Bug when building Polymer() in stk==2019.4.6.1

### ISSUE THREAD

**Issue by andrewtarzia** [lukasturcani/stk#8]
**Bug, feature request, or proposal:**

Bug

**Expected Behaviour:**

Building of Polymer() works in version 2019.4.3.0 from the 3 building blocks attached and the code below.

**Current behavior:**

MacroMoleculeBuildError() exception occurs using up-to-date version of stk from pip:

An error message comes up on Traceback: 

> RuntimeError: Pre-condition Violation
> 	bond already exists
> 	Violation occurred on line 284 in file Code/GraphMol/RWMol.cpp
> 	Failed Expression: !(boost::edge(atomIdx1, atomIdx2, d_graph).second)
> 	RDKIT: 2018.09.1
> 	BOOST: 1_65_1

**To reproduce:**

```
import stk

# load in molecules
core = stk.StructUnit('core.mol', ['bromine'])
liga = stk.StructUnit('liga.mol', ['bromine'])
link = stk.StructUnit('link.mol', ['bromine'])

# build molecule
    polymer = stk.Polymer([liga, link, core],
                          stk.Linear(repeating_unit='ABCBA',
                                     orientation=[0, 0, 0, 1, 1],
                                     n=1, ends='fg'))
# output as built
json_file = 'Test.json'
polymer.dump(json_file)
mol_file = 'Test.mol'
polymer.write(mol_file)
```

**I had to convert .mol files to .txt to upload, although I am sure there is a way around this.**
[core.txt](https://github.com/lukasturcani/stk/files/3055086/core.txt)
[liga.txt](https://github.com/lukasturcani/stk/files/3055087/liga.txt)
[link.txt](https://github.com/lukasturcani/stk/files/3055088/link.txt)

**Comment by lukasturcani** [comment]
Should be fixed in the latest commit.
