### ISSUE TITLE
Re-implemnt GFN optimzier to simply send args directly to command line

### ISSUE THREAD

**Issue by lukasturcani** [lukasturcani/stk#87]
Remove the temperature etc. args as keeping this up to date is too much hassle.

**Comment by lukasturcani** [comment]
assigning to @andrewtarzia

**Comment by andrewtarzia** [comment]
These calculators should now interface with the python API available from the xtb developers themselves so that no maintenance is required. I will implement these changes when possible as there is no easily available form of this API yet.

**Comment by lukasturcani** [comment]
Hmmm, I don't want to add a dependency to ase though, which looks like it might be necessary from the README. Any ideas on how to avoid this?

**Comment by andrewtarzia** [comment]
Would probably need to still have a calculator class (like that in ASE)
that interfaces with the XTB python library? That said, I would have to
look into that.

I guess that is effectively the same as what we already have, but if all of
the I/O to xtb runs through their python library, it diminishes the
maintenance we would have to do (I hope).

**Comment by lukasturcani** [comment]
After discussion with @andrewtarzia off-thread. GFN optimzier should just be replaced with a general ASEOptimizer.
