### ISSUE TITLE
write with set atom_ids produces mol file with wrong atom ids

### ISSUE THREAD

**Issue by andrewtarzia** [lukasturcani/stk#94]
Using stk.Molecule.write('MOLFILE', atom_ids=[]) writes out a mol file with atom ids matching those of the atoms prescribed by atom_ids parameter, but the bond ids are not matched to those and the molecule is not readable by Pymol (for example).

However, stk can read this mol file and rewrite it to a new mol file that is not broken.

**Comment by lukasturcani** [comment]
Fixed in #95
